-- RetainIQ Base Tables: Indian Motor Insurance Domain
-- Run after: 00_foundation.sql
USE DATABASE RETAINIQ_DB;
USE SCHEMA RAW;
USE WAREHOUSE RETAINIQ_WH;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID        VARCHAR(10)  NOT NULL,
    FIRST_NAME         VARCHAR(50)  NOT NULL,
    LAST_NAME          VARCHAR(50)  NOT NULL,
    AGE                INT,
    GENDER             VARCHAR(10),
    CITY               VARCHAR(50),
    STATE              VARCHAR(50),
    PIN_CODE           VARCHAR(6),
    PHONE              VARCHAR(15),
    EMAIL              VARCHAR(100),
    SEGMENT            VARCHAR(20),
    PREFERRED_LANGUAGE VARCHAR(20)  DEFAULT 'English',
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS POLICIES (
    POLICY_ID          VARCHAR(12)  NOT NULL,
    CUSTOMER_ID        VARCHAR(10)  NOT NULL,
    PRODUCT_TYPE       VARCHAR(30)  NOT NULL,
    VEHICLE_TYPE       VARCHAR(20),
    VEHICLE_MAKE       VARCHAR(30),
    VEHICLE_MODEL      VARCHAR(50),
    VEHICLE_YEAR       INT,
    PLAN_NAME          VARCHAR(50),
    SUM_INSURED        NUMBER(12,2),
    PREMIUM_AMOUNT     NUMBER(12,2) NOT NULL,
    PAYMENT_FREQUENCY  VARCHAR(15)  DEFAULT 'Annual',
    START_DATE         DATE         NOT NULL,
    END_DATE           DATE         NOT NULL,
    RENEWAL_DATE       DATE,
    STATUS             VARCHAR(15)  DEFAULT 'Active',
    NCB_PERCENTAGE     INT          DEFAULT 0,
    AUTO_RENEW         BOOLEAN      DEFAULT TRUE,
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (POLICY_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS CLAIMS (
    CLAIM_ID           VARCHAR(12)  NOT NULL,
    POLICY_ID          VARCHAR(12)  NOT NULL,
    CUSTOMER_ID        VARCHAR(10)  NOT NULL,
    CLAIM_DATE         DATE         NOT NULL,
    CLAIM_AMOUNT       NUMBER(12,2) NOT NULL,
    APPROVED_AMOUNT    NUMBER(12,2),
    STATUS             VARCHAR(15)  DEFAULT 'Pending',
    CATEGORY           VARCHAR(30),
    RESOLUTION_DATE    DATE,
    REJECTION_REASON   VARCHAR(500),
    NOTES              VARCHAR(500),
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLAIM_ID),
    FOREIGN KEY (POLICY_ID) REFERENCES POLICIES(POLICY_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID         VARCHAR(15)  NOT NULL,
    POLICY_ID          VARCHAR(12)  NOT NULL,
    CUSTOMER_ID        VARCHAR(10)  NOT NULL,
    DUE_DATE           DATE         NOT NULL,
    PAID_DATE          DATE,
    AMOUNT             NUMBER(12,2) NOT NULL,
    STATUS             VARCHAR(15)  DEFAULT 'Pending',
    PAYMENT_METHOD     VARCHAR(20),
    LATE_FEE           NUMBER(12,2) DEFAULT 0,
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (POLICY_ID) REFERENCES POLICIES(POLICY_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS INTERACTIONS (
    INTERACTION_ID     VARCHAR(15)  NOT NULL,
    CUSTOMER_ID        VARCHAR(10)  NOT NULL,
    CHANNEL            VARCHAR(15)  NOT NULL,
    DIRECTION          VARCHAR(10)  NOT NULL,
    INTERACTION_TS     TIMESTAMP_NTZ NOT NULL,
    SUBJECT            VARCHAR(200),
    CONTENT            VARCHAR(8000) NOT NULL,
    SUMMARY            VARCHAR(500),
    SENTIMENT_SCORE    FLOAT,
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (INTERACTION_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
